### ISSUE TITLE
/tmp/docspell-analysis getting quite big

### ISSUE THREAD

**Issue by JaCoB1123** [eikek/docspell#941] opened 2021-07-18 21:31 UTC
Hey eikek,

I just noticed that my /tmp/docspell-analysis in the docker overlay2 folder was 27GB big. I just recreated the whole docker stack and everything is fine again, so not an urgent issue.

Since it's in /tmp/ I guess these files are of no long-term importance. Maybe you could clean that folder up regularly?

Thanks, keep up the awesome work :+1:

**Comment by eikek** [comment] 2021-07-19 12:40
Hi @JaCoB1123 thank you for reporting this! This is really scary, of course. I just  looked at my installation which I restarted about 200 days ago. I cannot confirm this, on my machine the directory is empty (only a few regex files are there). I suspect therefore that this is something I missed to configure correctly in docker? This doesn't explain, why the files are not removed though! Could it be some permission problem? It is possible to set the temp dir to something else - what would be a good choice for docker (I think I can simply mount some directory on the host for this)?

**Comment by JaCoB1123** [comment] 2021-07-19 19:11
I just recreated my whole docker-compose stack and imported about a 100 documents. The overlay2 folder for the joex container grew from 40 to 180 MB. I'll keep an eye on it for a while. It seems to be growing steadily, it grew to 230 MB while writing this.

My docker-compose is quite normal I think. I'm using eikek0/docspell:joex-LATEST and my only volume is for the docspell.conf. 

Any ideas what I could check?

**Comment by JaCoB1123** [comment] 2021-07-19 19:19
I may have found the reason for the growing data usage.
My used disk space has grown to 335MB by now.
After checking the logs I noticed that joex keeps restarting and probably reanalyzes the same item over and over after the following exception:

```
joex_1        | java.lang.OutOfMemoryError: Java heap space                                                                                            
joex_1        |         at edu.stanford.nlp.classify.LogConditionalObjectiveFunction$CLBatchDerivativeCalculation.<init>(LogConditionalObjectiveFunctio
234)                                                                                                                                                   
joex_1        |         at edu.stanford.nlp.classify.LogConditionalObjectiveFunction.calculateCLbatch(LogConditionalObjectiveFunction.java:328)        
joex_1        |         at edu.stanford.nlp.classify.LogConditionalObjectiveFunction.calculateCL(LogConditionalObjectiveFunction.java:216)             
joex_1        |         at edu.stanford.nlp.classify.LogConditionalObjectiveFunction.calculate(LogConditionalObjectiveFunction.java:123)               
joex_1        |         at edu.stanford.nlp.optimization.AbstractCachingDiffFunction.ensure(AbstractCachingDiffFunction.java:138)                      
joex_1        |         at edu.stanford.nlp.optimization.AbstractCachingDiffFunction.valueAt(AbstractCachingDiffFunction.java:143)                     
joex_1        |         at edu.stanford.nlp.optimization.QNMinimizer.lineSearchMinPack(QNMinimizer.java:1453)                                          
joex_1        |         at edu.stanford.nlp.optimization.QNMinimizer.minimize(QNMinimizer.java:1020)                                                   
joex_1        |         at edu.stanford.nlp.optimization.QNMinimizer.minimize(QNMinimizer.java:871)                                                    
joex_1        |         at edu.stanford.nlp.optimization.QNMinimizer.minimize(QNMinimizer.java:865)                                                    
joex_1        |         at edu.stanford.nlp.optimization.QNMinimizer.minimize(QNMinimizer.java:93)                                                     
joex_1        |         at edu.stanford.nlp.classify.LinearClassifierFactory.trainWeights(LinearClassifierFactory.java:529)                            
joex_1        |         at edu.stanford.nlp.classify.LinearClassifierFactory.trainClassifier(LinearClassifierFactory.java:929)                         
joex_1        |         at edu.stanford.nlp.classify.LinearClassifierFactory.trainClassifier(LinearClassifierFactory.java:913)                         
joex_1        |         at edu.stanford.nlp.classify.ColumnDataClassifier.makeClassifier(ColumnDataClassifier.java:1482)                               
joex_1        |         at edu.stanford.nlp.classify.ColumnDataClassifier.trainClassifier(ColumnDataClassifier.java:2087)                              
joex_1        |         at docspell.analysis.classifier.StanfordTextClassifier.$anonfun$train$3(StanfordTextClassifier.scala:69)                       
joex_1        |         at docspell.analysis.classifier.StanfordTextClassifier$$Lambda$3300/0x0000000100d7c040.apply(Unknown Source)                   
joex_1        |         at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:104)                                 
joex_1        |         at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)                                                 
joex_1        |         at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:474)                                                    
joex_1        |         at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)                       
joex_1        |         at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)                                                             
joex_1        |         at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)                                     
joex_1        |         at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)                                
joex_1        |         at cats.effect.internals.TrampolineEC$JVMTrampoline$$Lambda$731/0x0000000100462040.apply$mcV$sp(Unknown Source)                
joex_1        |         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)                                                     
joex_1        |         at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)                                                      
joex_1        |         at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)                                           
joex_1        |         at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)                                                               
joex_1        |         at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)                                                           
joex_1        |         at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:482)                                                  
```

So it seems to be running out of memory. Any Ideas how I can work around that? I remember having to increase the Limits for Java Applications

**Comment by eikek** [comment] 2021-07-19 19:32
Ah that makes sense then. The OOM is probably caused by the high demands of the text analyzer (NLP). These options come to mind:

1. If you can afford it, give it more memory using `-Xmx` option, for example I'm using `-Xmx1500m` which gives the java heap 1.5G (the whole process needs more than this)
2. You can set `nlp.mode=basic` which reduces the memory footprint a lot, but is probably less accurate (I haven't measured this exactly) - see [here](https://docspell.org/docs/configure/#nlp) for some details. The results last time I tried were not too bad, though.
3. You can set `nlp.mode=regexonly` which lowers memory consumption even more. This then has not good results in creating suggestions for correspondents etc.

**Comment by JaCoB1123** [comment] 2021-07-19 20:41
I do have memory to spare, where would I use that `-Xmx` option?

I just stopped my joex and after waiting a bit I was able to delete the problematic job which was a big jpg image. So I guess it's fixed for me for the time being. It still might make sense to improve the error handling there, so those files are cleaned up even after an exception.

**Comment by eikek** [comment] 2021-07-19 20:54
The problem is, that an OOM is not a normal exception, but a virtual machine error. You *can* catch these, but if that really helps is not sure. The program may be in a bad state. On "normal" exceptions, joex would remove the files and also quit after a few tries. It is generally discouraged to react on these types of errors in your program, because everything may be at odds. 

Another option is to not restart the process forever, but to stop restarting after too many fails (systemd and things like that do this by default). You can also pass in an explicit temp directory and clean this up from the parent process, once the docspell process stopped. (now i have no clue how that works in docker …)

The `-Xmx` option must go to the startup command, before the config file. Try this: `bin/docspell-joex -J-Xmx1500m -- /path/to/config`.

**Comment by JaCoB1123** [comment] 2021-10-01 12:30
I just had the problem again, though I didn't see any OOM exceptions this time.

I hope I have fixed it now by using an addittional tmpfs mount for /tmp:

```
- type: tmpfs    
  target: /tmp   
  tmpfs:         
    size: 1000   
```

I'll report back, if it happens again.

**Comment by eikek** [comment] 2022-02-12 13:01
Closing this now; feel free to reopen if you think there can be something improved.

**Closed by eikek** 2022-02-12 13:01 UTC
Labels: question
