### ISSUE TITLE
Consumedir does not seem to work reliable

### ISSUE THREAD

**Issue by sandk4sta** [eikek/docspell#567] opened 2021-01-14 11:48 UTC
Hi eikek

First of all: I would like to thank you for this cool project! I was looking out there for ages for a DMS like this, the functions work in general like a charm and makes real fun. It's amazing!

I just have one issue what drives me crazy. In order to get the full picture I would like to let you my setup know:

- Original files come to a specified NextCloud directory; which is hosted on a separate ProxMox Server
- Scanned files being pushed using rsync to the host server where DocSpell is actually running
- DocSpell has been installed using Docker-Compose; running several containers with DocSpell dependencies
_- DocSpell/Consumedir watches the "docs/collection" directory_

Here the issue comes across. In general it works quite well and Consumedir watches the directory and pushes new items to DocSpell. But in the last few days ConsumeDir pushed some items to DocSpell which already have been processed (creating duplicates in DocSpell) or it takes ages till the new items are processed. I am not sure in which time interval Consumedir (in a Docker installation) watches the directory but it took around 10 hours to get it pushed to DocSpell.

Any thoughts how the setup can be optimized? Not sure, where the issue is being occured.

Many thanks for your feedback, which is highly appreciated!

Best, sandk4sta

**Comment by eikek** [comment] 2021-01-14 16:59
Hi @sandk4sta , thank you very much for your kind words! Glad you like it!

I'm sorry that the consumedir doesn't work well for you. I have not a good idea, why that doesn't work in this case. The consumedir uses inotify to get notified whenever a new file has been saved. It then uploads it via curl to an http endpoint. So there is no polling involed, files should get into docspell quite fast. Is this always happening, can you think of some pattern? Like, is the behaviour reproducible by moving files into this directory from a local dir?

If the problem is with inotify, one could run `consumedir` a periodically to upload all files in there. But we need to find out first :-)

Do you see something in the logs when files are copied by rsync? Is the filesystem, where the files arrive to be consumed by consumedir container, a local filesystem (or a remote, like nfs or samba)?

A mini optimization might be to move the consumedir to the proxmox server, if that is possible (the consumedir is very lightweight). So instead of using rsync, consumedir can directly upload files to some other machine running docspell. This would remove one thing in the setup….

**Comment by sandk4sta** [comment] 2021-01-21 08:43
Hi @eikek 

Many thanks for your prompt reply! That was unbelievable fast & sorry for my delay in getting back to you. 

In the meantime, I have changed my setup slightly and now it seems to work reliable. My setup is now as follows:

- Consumedir runs as a service on the Nextcloud machine, pushes every new file to Docspell
- Docspell runs via Docker (setup with Docker Compose, without the Consumedir Container)

In order to setup Consumedir on the Nextcloud machine I followed your documentation. However, in order to enable the Consumedir service to run once booted the service file has to be amended, one part has to be added (don't have it by hand as I am mobile). I would appreciate if you could update the documentation so that other users don't run in the same issue. 

Again, many thanks for the good work!!

BTW, two more questions:

- If I export everything using the export tool - how can I import all these files in another Docspell instance?
- How can I properly update Docspell to the latest version without loosing data?

Best, sandk4sta

**Comment by eikek** [comment] 2021-01-21 17:21
> Many thanks for your prompt reply! That was unbelievable fast & sorry for my delay in getting back to you.

You are welcome, and don't worry about delays!


> In the meantime, I have changed my setup slightly and now it seems to work reliable. My setup is now as follows:
> 
>     * Consumedir runs as a service on the Nextcloud machine, pushes every new file to Docspell
> 
>     * Docspell runs via Docker (setup with Docker Compose, without the Consumedir Container)

I think, this is a better setup. The consumedir is very lightweight on purpose, so that you can run it on many machines. For example, I have it also running on our laptops so that we can download things into a specific folder that then gets into docspell immediately.


> I would appreciate if you could update the documentation so that other users don't run in the same issue.

Yes, definitely, thank you. Could you maybe provide this part you added? Was it maybe `WantedBy: multi-user.target`? I just saw, that this is missing. IIRC this would let systemd start the service on boot to reach "multi-user" target.


>     * If I export everything using the export tool - how can I import all these files in another Docspell instance?

This is currently not possible. It is provided mainly for people who are afraid that their documents get locked up in docspell. It allows to get them all out (via some script periodically) into the filesystem. There is no import/export thing yet (it's on my list, though, but no eta…). This is currently "delegated" to the database. All supported dbms have backup/restore features. You could restore a db dump from one docspell instance to another.


>     * How can I properly update Docspell to the latest version without loosing data?

This is done automatically. When a new version starts up it migrates the database schema automatically to the current version. Data is not lost. I'm testing the migration for all dbms before doing a release, but despite this, it's always a good idea to make a backup before (using pg_dump), since mistakes and bugs happen (I would recommend this for any tool, in fact). In general, you can just pull the new docker image and start it up.

**Comment by tinkerdudeno1** [comment] 2021-01-24 12:55
I have one addition to this issue: Consumedir (or rather inotify) does not work well/at all on CIFS shares. Which is a bummer because I have a network share that my scanner is sending files to and I cannot watch this dir directly since docspell is not running on the same machine. I am now syncing the docs from the shre with rsync to a local dir and consumedir works like a charm. Took me a while to figure that one out, though. Maybe someone else will stumble upon this caveat so I thought I'd share this here.
Oh and: Great project! Been trying around with other document management systems and docspell is just as lightweight as I need it to be. Just like you write in your docs: For people how want to keep their docs in a file system and still be able to search through them efficiently. Very, very cool, thanks for sharing this!

**Comment by eikek** [comment] 2021-01-24 14:34
Hi @tinkerdudeno1 – thanks a lot for your input and kind words.

You just made me realize, that I should put more info into the docs regarding consumedir and network filesystems, regarding the possible options. It's true that inotify doesn't work in this case. There are these ways around:

- Remove consumedir from the machine that runs docspell and put it on the machine that receives the files, where you can watch the *local* filesystem. So whatever exposes the share should run the consumedir part (if that is possible, if you own the machine it should be). If you use the docker-compose setup, just remove the consumedir container from the compose file and run it on the machine exposing the share instead.
- Run consumedir periodically in its other mode where it simply loops through the filesystem and uploads what it finds, this is without inotify. This is of course not as nice, but could also be sufficient depending on the use case etc.

I would always try the first, as it is more convenient. It is totally fine to run multiple consumedirs on the same machine or on different machines.

**Comment by JaCoB1123** [comment] 2021-01-26 14:51
Hi @eikek,

I'm also having some problems with consumedir. After realizing, that it doesn't work with a NFS mount I set it up to check every 5 minutes using ofelia. With the last update it stopped working though, because apparently consumedir.sh isn't executable any more? I fixed that temporarily by reverting to consumedir-v0.18.0.

Additionally I'd love to see an option for polling regularly so I don't have to rely on ofelia any more. This would also simplify the setup for anyone using a remote filesystem.

Best,
jacob

**Comment by eikek** [comment] 2021-01-26 19:05
Hi @JaCoB1123 , ok I see. You can't run the consumedir bash script on the machine that is exposing the shares? The bash script should run on many linuxes and is rather lightweight.

You found consumedir not working anymore? Oh that would be a bug. I did move it into another directory. Maybe you need to update the path? The docker image should work, at least I tried it once. If it's still not working, you can open an issue.

Hm not so sure what to do. I'm not sure if it's a good idea to add polling directly to the consumedir script. You can ,for example, use the `watch` command or systemd (which is on most linuxes today anyways). I never heard of ophelia. If you want simply a process that always runs, something like

```
watch -n 300 ./path/to/consumedir.sh [options]
```
or with a loop
```
for ((;;)); do ./path/to/consumedir.sh [options] done
```
could work? Well, you're right, if this is a major use case something more convenient is necessary. Maybe an additional option to the script is ok. I'll think about it.

**Comment by JaCoB1123** [comment] 2021-01-26 19:38
Yes, I had multiple messages about consumedir.sh not being executable (or missing permissions) in the logfile. Manually executing chmod +x would probably have solved it as well.

Unfortunately the files reside on another server that I must not install anything on.

I'd prefer to run consumedir in docker as well, that's why I used ofelia, which is so to say "cron for docker". Maybe you could add another batch script to the image that does exactly that for loop with an added sleep? I could try adding that, if that's acceptable for you.

**Comment by eikek** [comment] 2021-01-26 19:46
You mean the docker image for consumedir is not working for 0.19.0 "out of the box"? That's strange,  I tested this afaik… I have to look at it. It must of course work without manually fiddling:)


> Maybe you could add another batch script to the image that does exactly that for loop with an added sleep? I could try adding that, if that's acceptable for you.

Yes, sure. You can add another script or an option to the current consumedir script. A new script would be simpler probably, as the consumedir is already quite large. But either way is fine to me.

**Comment by antifuchs** [comment] 2021-01-30 15:55
Chiming in on this issue, I just finished importing a few hundred PDFs, and I might have an idea why duplicates happen (this isn't via the consumedir, but I think it's the same root cause, maybe): 

When importing the PDFs, I used `ds` to add a few dozen documents first (all the ones from 2012); then added "all" the documents in the directory. As the queue hadn't finished processing the first few dozen when I added "all" of them, the documents that weren't processed got added to the queue again. Once it was their turn to get processed, they did get added a second time, and ended up as duplicates in the database.

So, my understanding of this is that if a document in the consumedir gets matched multiple times (either via faulty fs notifications, or via the consumedir cleaner process) and the first match is still in the processing queue, the API will happily accept a duplicate submission. Could the presence of a doc on the queue be checked at submission time, to avoid this problem?

**Comment by eikek** [comment] 2021-01-30 16:15
> As the queue hadn't finished processing the first few dozen when I added "all" of them, the documents that weren't processed got added to the queue again. Once it was their turn to get processed, they did get added a second time, and ended up as duplicates in the database.

Yes, this is true. The queue is currently not checked for files. However, if you only have one job processing at a time, all files get processed sequentially and the job will (if told so) check again for duplicates when processing. So in this case, duplicates shouldn't happen.  Since duplicates happen, there is some bug in the `ds` or `consumedir` script. They should add the required parameter to the upload request. Did you use `consumedir` or `ds` only? I suspect it's missing in the `ds` script…



> Could the presence of a doc on the queue be checked at submission time, to avoid this problem?

It would be possible, but is a bit tricky. The queue is a "generic" job queue, that doesn't know about files etc. Since most users (probably) have only a single job executor, I'd say that it's enough (given the bugs are gone:)).

**Comment by eikek** [comment] 2021-02-26 17:46
I updated the docs to be more verbose on the consumdir: https://docspell.org/docs/tools/consumedir/#network-filesystems-samba-cifs-nfs Then there is a new issue to fix the ds script to tell the processing jobs to skip duplicates. And thanks to @JaCoB1123 the consumedir docker image can now conveniently work in "polling mode" since 0.20.0.

I'm closing this issue, but if there are more questions or things I can help with, or things I forgot to digest, let me know! :-) Thanks!

**Closed by eikek** 2021-02-26 17:46 UTC
Labels: question
