### ISSUE TITLE
Error while upgrading database from 0.32.0 to 0.34.0

### ISSUE THREAD

**Issue by ohagene** [eikek/docspell#1488] opened 2022-04-03 11:17 UTC
I have just pulled the new 0.34.0 docker containers and after starting them I can't connect to the website and I see the following in logs.

```
docspell-restserver  | Apr 03, 2022 10:37:31 AM org.jline.utils.Log logr
docspell-restserver  | WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
docspell-restserver  | 2022.04.03 10:37:31:035 io-compute-6 INFO docspell.config.ConfigFactory.default:44
docspell-restserver  |     Using config from environment variables!
docspell-restserver  | 2022.04.03 10:37:31:781 io-compute-6 WARN docspell.restserver.ConfigFile.generateSecretIfEmpty:57
docspell-restserver  |     No serverSecret specified. Generating a random one. It is recommended to add a server-secret in the config file.
docspell-restserver  | 2022.04.03 10:37:31:0000 [io-comp...] [INFO ] docspell.restserver.Main.run:34 -
docspell-restserver  | ***>  ______                          _ _
docspell-restserver  | ***>  |  _  \                        | | |
docspell-restserver  | ***>  | | | |___   ___ ___ _ __   ___| | |
docspell-restserver  | ***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
docspell-restserver  | ***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
docspell-restserver  | ***>  |___/ \___/ \___|___/ .__/ \___|_|_|
docspell-restserver  | ***>                      | |
docspell-restserver  | ***>                      |_| v0.34.0 (#c6da3eb0)
docspell-restserver  | ***>  << REST Server >>
docspell-restserver  | ***>  Id:       rest1
docspell-restserver  | ***>  Base-Url: http://localhost:7880
docspell-restserver  | ***>  Database: jdbc:postgresql://xxxx:5432/docspell
docspell-restserver  | ***>  Fts:      PostgreSQL(default)
docspell-restserver  | ***>  Config:
docspell-restserver  | ***>  FileRepo: DefaultDatabase(true)
docspell-restserver  | ***>
docspell-restserver  | 2022.04.03 10:37:32:0000 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.createFlyway:37 - Creating Flyway for: List(classpath:db/fixups/postgresql, classpath:db/fixups/common)
docspell-restserver  | 2022.04.03 10:37:32:0001 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.runFixups:64 - !!! Running fixup migrations
docspell-restserver  | 2022.04.03 10:37:32:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 8.5.4 by Redgate
docspell-restserver  | 2022.04.03 10:37:32:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.4
docspell-restserver  | 2022.04.03 10:37:32:0004 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter -
docspell-restserver  | 2022.04.03 10:37:32:0005 [io-comp...] [INFO ] org.flywaydb.core.internal.database.base.BaseDatabaseType - Database: jdbc:postgresql://data-01:5432/docspell (PostgreSQL 14.1)
docspell-restserver  | 2022.04.03 10:37:32:0006 [io-comp...] [INFO ] org.flywaydb.core.internal.command.DbValidate - Successfully validated 2 migrations (execution time 00:00.024s)
docspell-restserver  | 2022.04.03 10:38:24:0000 [io-comp...] [ERROR] org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate - Unable to release PostgreSQL advisory lock
docspell-restserver  | 2022.04.03 10:38:24:0000 [io-comp...] [INFO ] org.http4s.blaze.client.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
docspell-restserver  | org.flywaydb.core.api.FlywayException: Number of retries exceeded while attempting to acquire PostgreSQL advisory lock. Configure the number of retries with the 'lockRetryCount' configuration option: https://rd.gt/3A57jfk
docspell-restserver  |  at org.flywaydb.core.internal.strategy.RetryStrategy.doWithRetries(RetryStrategy.java:87)
docspell-restserver  |  at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.lock(PostgreSQLAdvisoryLockTemplate.java:87)
docspell-restserver  |  at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:68)
docspell-restserver  |  at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
docspell-restserver  |  at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
docspell-restserver  |  at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
docspell-restserver  |  at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
docspell-restserver  |  at org.flywaydb.core.Flyway$1.execute(Flyway.java:172)
docspell-restserver  |  at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
docspell-restserver  |  at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:205)
docspell-restserver  |  at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
docspell-restserver  |  at docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$5(FlywayMigrate.scala:65)
docspell-restserver  |  at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
docspell-restserver  |  at map @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$4(FlywayMigrate.scala:65)
docspell-restserver  |  at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:28)
docspell-restserver  |  at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$2(FlywayMigrate.scala:64)
docspell-restserver  |  at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:28)
docspell-restserver  |  at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:37)
docspell-restserver  |  at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:37)
docspell-restserver  |  at flatMap @ docspell.store.migrate.FlywayMigrate.createFlyway(FlywayMigrate.scala:36)
docspell-restserver  |  at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$1(FlywayMigrate.scala:63)
docspell-restserver  |  at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
docspell-restserver  |  at as @ docspell.restserver.RestServer$.$anonfun$serve$1(RestServer.scala:67)
docspell-restserver  |  at $anonfun$apply$10 @ fs2.Stream$.$anonfun$resourceWeak$3(Stream.scala:3624)
docspell-restserver  |  at $anonfun$apply$10 @ fs2.Stream$.$anonfun$resourceWeak$3(Stream.scala:3624)
docspell-restserver  |  at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
docspell-restserver  |  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
docspell-restserver  |  at $anonfun$apply$10 @ fs2.Stream$.$anonfun$resourceWeak$3(Stream.scala:3624)
docspell-restserver exited with code 0
```

**Comment by eikek** [comment] 2022-04-04 09:12
Hi! the error tells that some other flyway process is currently running. Did you start both containers and the other is still doing migrations maybe? Could you try to only start one container to see if that produces different output? Depending on how many files you have, there is a migration in 0.33.0 that could take a while to complete.

**Comment by ohagene** [comment] 2022-04-08 06:28
Hi! I just start restserver container alone, and it output the same log. I have 80k+ file, so might be there is a timeout problem?
Can I manually upgrade the database?

**Comment by eikek** [comment] 2022-04-08 16:42
Hi @ohagene - wow 80k file is quite a lot! This could really take a while to complete (on my machine it took ~1min for ~8000 files). The message about a held advisory lock means that there is still another session open that holds this lock - can this be? Is there maybe joex still running or something like that? You can query all locks via `SELECT * from pg_locks` - maybe it shows something?

The advisory locks are cleared automatically at the end of the session. So a brute-force way would be to stop postgres (or killing all sessions). Then start only restserver - it should now be able to grab the lock and since there is no other process connected to postgres, it should succeed.

**Comment by TheAnachronism** [comment] 2022-04-15 00:28
Mhh so I'm going through the update process now, but I can't make it past version 33. I run docspell with docker-compose, but if I upgrade the restserver and joex to v0.34.0 and restart everything, I get the `Validate failed: Migrations have failed validation` error.
In another Issue @eikek mentioned, that going through each version step by step would be a good workaround, but there still seems something wrong with the database migrations.

Any ideas on this?

```
2022.04.15 02:25:15:0000 [io-comp...] [INFO ] org.http4s.blaze.client.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Migration checksum mismatch for migration version 1.33.0
-> Applied to database : 1776159438
-> Resolved locally    : 1347412019
Either revert the changes to the migration, or run repair to update the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:130)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:205)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
	at docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$5(FlywayMigrate.scala:65)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$4(FlywayMigrate.scala:65)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:28)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$2(FlywayMigrate.scala:64)
	at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:28)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:37)
	at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:37)
	at flatMap @ docspell.store.migrate.FlywayMigrate.createFlyway(FlywayMigrate.scala:36)
	at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$1(FlywayMigrate.scala:63)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at as @ docspell.restserver.RestServer$.$anonfun$serve$1(RestServer.scala:67)
	at $anonfun$apply$10 @ fs2.Stream$.$anonfun$resourceWeak$3(Stream.scala:3624)
	at $anonfun$apply$10 @ fs2.Stream$.$anonfun$resourceWeak$3(Stream.scala:3624)
	at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:162)
	at $anonfun$apply$10 @ fs2.Stream$.$anonfun$resourceWeak$3(Stream.scala:3624)
```

**Comment by enkol** [comment] 2022-04-15 13:23
I get the same error as @TheAnachronism. I'm running with docker, tag latest, so it tried updating from v0.34.0 to v0.35.0 but it stopped with the same 1.33.0 migration error. However, for me, migration missmatch checksums are flipped between applied and locally resolved.

Changing from latest to fixed version v0.34.0 it works again.

```
***>  ______                          _ _
***>  |  _  \                        | | |
***>  | | | |___   ___ ___ _ __   ___| | |
***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
***>  |___/ \___/ \___|___/ .__/ \___|_|_|
***>                      | |
***>                      |_| v0.35.0 (#f5958b3a)
***>  << REST Server >>
***>  Id:       ***
***>  Base-Url: ***
***>  Database: jdbc:***
***>  Fts:      PostgreSQL(default)
***>  Config:   /opt/docspell.conf
***>  FileRepo: DefaultDatabase(true)
***>  
2022.04.15 15:03:15:0001 [io-comp...] [INFO ] docspell.restserver.RestServer.serve:46 - Starting server with options ServerOptions(Duration(45000ms),false,1024)
2022.04.15 15:03:16:0000 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.createFlyway:38 - Creating Flyway for: List(classpath:db/fixups/postgresql, classpath:db/fixups/common)
2022.04.15 15:03:16:0001 [io-comp...] [INFO ] docspell.store.migrate.FlywayMigrate.runFixups:69 - !!! Running fixup migrations
2022.04.15 15:03:16:0002 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 8.5.8 by Redgate
2022.04.15 15:03:16:0003 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#8.5.8
2022.04.15 15:03:16:0004 [io-comp...] [INFO ] org.flywaydb.core.internal.license.VersionPrinter - 
2022.04.15 15:03:16:0005 [io-comp...] [INFO ] org.flywaydb.core.internal.database.base.BaseDatabaseType - Database: jdbc:***(PostgreSQL 14.2)
2022.04.15 15:03:17:0000 [io-comp...] [INFO ] org.http4s.blaze.client.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Migration checksum mismatch for migration version 1.33.0
-> Applied to database : 1347412019
-> Resolved locally    : 1776159438
Either revert the changes to the migration, or run repair to update the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:130)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:205)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
        at docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$8(FlywayMigrate.scala:70)
        at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
        at liftF @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$4(FlywayMigrate.scala:68)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$7(FlywayMigrate.scala:70)
        at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:28)
        at liftF @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$4(FlywayMigrate.scala:68)
        at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$1(FlywayMigrate.scala:64)
        at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:28)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:38)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:38)
        at flatMap @ docspell.store.migrate.FlywayMigrate.createFlyway(FlywayMigrate.scala:37)
        at liftF @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$4(FlywayMigrate.scala:68)
        at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$1(FlywayMigrate.scala:64)
        at filter @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$2(FlywayMigrate.scala:67)
        at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$1(FlywayMigrate.scala:64)
        at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
        at as @ docspell.restserver.RestServer$.$anonfun$serve$4(RestServer.scala:70)
```

**Comment by eikek** [comment] 2022-04-15 18:10
I'm sorry  - this is really getting annoying. The migration did not change, I don't know why it calculates different checksums.

In my database, I have the checksum `1347412019`. Interestingly I had no problem to upgrade. This is affecting this "fixup migration", I think we can simply remove the row from the migration history: 
```
DELETE FROM flyway_fixup_history WHERE checksum = '1347412019'
```
(or the other checksum). This will apply the migration again. Another way is to simply fix the checksum in the db with an 
```
UPDATE flyway_fixup_history SET checksum = '…' where checksum = '…'
```
since it has been applied before, this is ok here. Note, this applies to the checksum problem - it is different to that @ohagene has described!

**Comment by Skyr** [comment] 2022-04-16 09:28
Same problem here. Tried the "DELETE FROM" from above, this causes a looong list of migration checksum failures (back to 1.0.0).

**Comment by ohagene** [comment] 2022-04-16 09:53
@eikek Hi, thank you very much! Finally, it worked! I restarted the postgresql db, and started only restserver container, after about a half day, it successed!

**Comment by eikek** [comment] 2022-04-16 11:01
Thank you @ohagene for the update, I was really curious with this large amount of files. Half a day is pretty long. still. Glad it worked.

@Skyr oh that means something is wrong! Are you sure you are deleting from `flyway_fixup_history`? There are other `flyway_*` tables that must not be touched. 

To me it is still not clear why the checksum changed. The migration was not changed and as far as I can see [here](https://github.com/flyway/flyway/blob/flyway-8.5.8/flyway-core/src/main/java/org/flywaydb/core/internal/resolver/ChecksumCalculator.java) the checksum algorithm only looks at the migration contents. It would be also ok to completely drop the `flyway_fixup_history` table (only this one!) and restart.

**Comment by enkol** [comment] 2022-04-16 13:01
@eikek I've tried deleting/updating fixup history as suggested, but with v0.35.0 it results in the same problem, just fails on all migration checksum checks from 1.0.0 on (as @Skyr mentioned).

Going back to v0.34.0 after deleting the fixup history entry works and Docspell runs fine again. 

```
2022.04.16 14:11:58:0000 [io-comp...] [INFO ] org.http4s.blaze.client.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false
org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Migration checksum mismatch for migration version 1.0.0
-> Applied to database : 317337288
-> Resolved locally    : -118882639
Either revert the changes to the migration, or run repair to update the schema history.
Migration checksum mismatch for migration version 1.1.0
-> Applied to database : 655930044
-> Resolved locally    : -1102699734

<<< snipped long list >>>

Either revert the changes to the migration, or run repair to update the schema history.
Migration checksum mismatch for migration version 1.33.0
-> Applied to database : 1583732153
-> Resolved locally    : 924153984
Either revert the changes to the migration, or run repair to update the schema history.
Migration checksum mismatch for migration version 1.34.0
-> Applied to database : -146289187
-> Resolved locally    : -750119324
Either revert the changes to the migration, or run repair to update the schema history.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:130)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:205)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:124)
        at docspell.store.migrate.FlywayMigrate.$anonfun$run$5(FlywayMigrate.scala:54)
        at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$run$4(FlywayMigrate.scala:54)
        at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:28)
        at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$run$2(FlywayMigrate.scala:53)
        at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:28)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:38)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$createFlyway$1(FlywayMigrate.scala:38)
        at flatMap @ docspell.store.migrate.FlywayMigrate.createFlyway(FlywayMigrate.scala:37)
        at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$run$1(FlywayMigrate.scala:52)
        at blocking @ fs2.io.file.FilesCompanionPlatform$AsyncFiles.exists(FilesPlatform.scala:204)
        at liftF @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$4(FlywayMigrate.scala:68)
        at map @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$7(FlywayMigrate.scala:70)
        at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:28)
        at liftF @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$4(FlywayMigrate.scala:68)
        at flatMap @ docspell.store.migrate.FlywayMigrate.$anonfun$runFixups$1(FlywayMigrate.scala:64)
        at delay @ docspell.logging.impl.ScribeWrapper$Impl.log(ScribeWrapper.scala:28)
```

**Comment by enkol** [comment] 2022-04-16 13:04
@eikek  Should I open a different issue, as this checksum problem seems to be different from the original issue here and also seems to be related to v0.35.0?

**Comment by eikek** [comment] 2022-04-16 13:20
Yes, I think it's better - I created a new issue #1517.

**Comment by TheAnachronism** [comment] 2022-04-16 13:50
OK, so I managed to upgrade to 0.34.0 by dropping the migration-history table. But the upgrade from 34 to 35 still fails. I also tried the same workaround (dropping the migration table) but that won't work either.

**Comment by eikek** [comment] 2022-04-16 17:33
Hi @TheAnachronism thanks for the update. I'll investigate it now under #1517  in the next days.

**Comment by TheAnachronism** [comment] 2022-05-25 22:06
@eikek Did you find anything?
Either way, I guess this issue can be closed as it gets handled in the other one.

**Comment by eikek** [comment] 2022-05-25 22:16
@TheAnachronism yes we found the cause of the checksum problem. #1517 has all the details. It is a "broken" zlib in the image. This issue was originally about another problem and this got solved I think: https://github.com/eikek/docspell/issues/1488#issuecomment-1100624619 

So I can as well close this one right away.

**Closed by eikek** 2022-05-25 22:16 UTC
Labels: question
