### ISSUE TITLE
I'm using Chrome: 88.0.4324.96

### ISSUE THREAD

**Issue by voarsh2** [eikek/docspell#688] opened 2021-03-07 19:43 UTC
I'm using this version of Chromium and above: 88.0.4324.96
I am the navigation on the right side  (profile, processing data, etc) I cannot click on them.
No problem on Chromium Edge though.

**Comment by eikek** [comment] 2021-03-07 19:59
Hi @voarsh2; I have chromium Version 88.0.4324.182 and can't reproduce it there. You mean the navigation menu on the "Manage Data" page? Are these the only links that don't work? How about the link on the item list page, can you select tags and unfold all the fields there? I really don't know what could cause this.

**Comment by voarsh2** [comment] 2021-03-09 21:10
> Oh my…! Elm, the frontend tech I'm using here, should make errors like these impossible :)
> 
> This is most probably due to something external messing with the dom, that Elm wants to own exclusively. I suspect some browser extension maybe? Could you try the same version without any extensions?

Haha.

I found the culprit extension.
https://chrome.google.com/webstore/detail/abkfbakhjpmblaafnpgjppbmioombali

I have a workaround, my chromium (not official Chrome) can enable/disable certain extensions based on a "profile" which I can set for specific sites/apps. So, I'll disable this extension for a profile I'll use just for Docspell. :)

**Comment by eikek** [comment] 2021-03-09 21:35
Great you found it! That's a bit of bad luck. It's not really possible to guard against extensions like these. If something from the "outside" is changing the dom, the app could break. That applies to all these vdom based frameworks, I guess. Maybe it can be improved a little by not owning the `body` element…. But I'm not sure if I can actually control this. And it wouldn't catch all extensions anyways. I think your workaround is a very good one :-)

**Comment by eikek** [comment] 2021-03-11 07:27
I think we can close this. There's not much I can do. For now the app requires exclusive access to the dom; and therefore may not be compatible with certain third-party browser extensions.

**Closed by eikek** 2021-03-11 07:27 UTC
