### ISSUE TITLE
Person Dropdowns not working/empty

### ISSUE THREAD

**Issue by mardom1** [eikek/docspell#605] opened 2021-01-28 09:12 UTC
Hi,

Love the project so far!

While wanting to assign persons (both corresponding and concerning), I came across the problem that I cannot select previously created persons. The dropdowns are all empty (also in the filter area).

The persons are however present in the data management interface and the ajax request also returns the correct list. It seems to be an UI issue. I also tried assigning an organization to persons with no luck.

If additional information is needed, I am happy to help.

Best regards,
Marcel

**Comment by eikek** [comment] 2021-01-28 12:13
Hi, 

hm, it may be related to the organization setting. I think I filtered all persons *not* belonging to an organization. But if you remove teh organization, you should be allowed to set all persons.

But this doesn't explain the situation for the concerned person. Here it may be that the flag "concerned person only" must be set.

**Comment by mardom1** [comment] 2021-01-28 12:41
Interesting. I just played around a bit.

Turns out. If I tick "Use for concerning person suggestion only", the person shows up in the as a concerning person. If unchecked and assigned to an organization, the person shows up in the correspondent person dropdown. If neither "Use for concerning person suggestion only" is checked and no organization is assigned, the person does not show up anywhere.

That case should either be handled differently (maybe show up in both?), or be completely eliminated.

**Comment by eikek** [comment] 2021-01-28 14:38
Well, I think the UI should help here better! It is indeed non-obvious if you are not prepared to it. If on an item detail and an organization has been set, then only persons are listed that belong to that organization. The idea is to make it harder to assign persons and organizations that don't match (well, that worked I guess:)). So when you remove the organization _from the item_ then all persons are "unlocked". I hope this makes sense?

**Comment by mardom1** [comment] 2021-01-28 16:45
I think we are talking about different situations. My problem is when the person is *not* marked as "Use for concerning person suggestion only". In this case the person does not show in the *concerning person* dropdown. In fact the person is not shown in *any* person dropdown if the checkbox is *unchecked*. That makes the checkbox useless, as is it *has to be checked* to be usable. The "only" in the checkbox description suggests that the person would show up in both people fields if left unchecked.

![image](https://user-images.githubusercontent.com/32371724/106169364-97cdda00-618f-11eb-8341-d1830320f392.png)
![image](https://user-images.githubusercontent.com/32371724/106169255-766cee00-618f-11eb-9dfd-faecab8e32c3.png)

**Comment by eikek** [comment] 2021-01-28 20:02
> My problem is when the person is _not_ marked as "Use for concerning person suggestion only". In this case the person does not show in the _concerning person_ dropdown.

This is intended. It was changed at some point to only show concerning person only. The idea was that it fwas confusing to set person thought for correspondents as concerning. 


> In fact the person is not shown in _any_ person dropdown if the checkbox is _unchecked_.

Oh, this is strange and not intended. But I could not reproduce it. When I save a person without this flag (as in your sceenshot), it is selectable for the correspondent. It would only then be invisble if the item has an organization set, where no person is related to. I added a gif, not sure if I can explain with words…

![bug-2021-01-28_20 56 46](https://user-images.githubusercontent.com/701128/106192155-1769a200-61ac-11eb-98ad-6be3f2164370.gif)

**Comment by vakilando** [comment] 2021-01-28 20:05
Yes, indeed a bit mysterious... I've just tested:

- If "Use for concerning person suggestion only" is checked, the person shows up in the as a concerning person.
- If "Use for concerning person suggestion only" is not checked, the person does not show up in the as a concerning person.

The option  "Use for concerning person suggestion **_only_**" suggests that, if _not_ checked the person should show up as concerning _and_ correspondant.

- If unchecked and assigned to an organization, the person shows up in the correspondent person dropdown if the person belongs to the chosen organization.
- If neither "Use for concerning person suggestion only" is checked and no organization is assigned, the person **does** show up in the correspondent person dropdown _if no organization is chosen_.

**Comment by eikek** [comment] 2021-01-28 20:11
Thanks @vakilando , much better explained :) Yes this is currently the intended behaviour. I'm open to changes. I agree that it is really confusing when new to it. Maybe it would already suffice to make the text to the flag clearer?

For the correspondent:I kind of like it that you can select an organization and then only see persons related to it. If you want to set any corresponding person, you can remove the organization first.

For concerning: The idea was that it usually doesn't make much sense to be able to select from all persons. But I might simply miss a use case here. Do you want to be able to set any person as concerning? It is only a ui filter.

**Comment by mardom1** [comment] 2021-01-28 20:40
Thanks @vakilando, that is what I am experiencing as well.

> For the correspondent:I kind of like it that you can select an organization and then only see persons related to it. If you want to set any corresponding person, you can remove the organization first.

Yes, should definitely stay that way.

> For concerning: The idea was that it usually doesn't make much sense to be able to select from all persons. But I might simply miss a use case here. Do you want to be able to set any person as concerning? It is only a ui filter.

I like the idea, the implementation could be a bit clearer. Maybe change the checkbox to a radio group where you can select which type of person it is (corresponding, concerning, maybe both)? This way, it is clear where it will show up. I personally don't have a use case for the "both" option yet, but it doesn't hurt either.

**Comment by vakilando** [comment] 2021-01-28 20:47
> For concerning: The idea was that it usually doesn't make much sense to be able to select from all persons. But I might simply miss a use case here.

Well, difficult decision... I also like the idea and I like that the dropdown would be filled with less persons, but I just had a use case:
My mother wrote me a letter and sent me some contract documents. So she was the corespondant and I the concerning person.
Another day I bought something for my mother...........she was then the concerning person........

**Comment by eikek** [comment] 2021-01-28 21:40
Ah yes, good use case. I also like the idea with the radio group! The 'both' case requires to change the person model a bit, but that is something I wanted to do anyways.

**Closed** 2021-02-16 22:32 UTC
Labels: datamodel, joex, restserver, web-ui
