### ISSUE TITLE
Long documents fail

### ISSUE THREAD

**Issue by Lucki** [eikek/docspell#297] opened 2020-10-01 13:51 UTC
I've uploaded a whole folder and one document failed. It's a document with 45 pages about updated terms and conditions.

Copied errors from the processing page:

~~~
execution failed. Retrying later.: (conn=3836) Data too long for column 'content' at row 1
execution failed. Retrying later.: (conn=3775) Cannot delete or update a parent row: a foreign key constraint fails (`docspell`.`attachment_source`, CONSTRAINT `attachment_source_ibfk_1` FOREIGN KEY (`file_id`) REFERENCES `filemeta` (`id`))
execution failed. Retries exceeded.: (conn=3796) Cannot delete or update a parent row: a foreign key constraint fails (`docspell`.`attachment_source`, CONSTRAINT `attachment_source_ibfk_1` FOREIGN KEY (`file_id`) REFERENCES `filemeta` (`id`))
~~~

Although the document failed and isn't displayed anywhere in the UI it's blocking the reupload with the option "Skip files already present in docspell" set.

Unsetting the skip option allowed me to upload it and see it but everything related to the content wasn't available:

~~~
execution failed. Retrying later.: (conn=3836) Data too long for column 'content' at row 1
Found existing item with these files.
execution failed. Retrying later.: 0
Found existing item with these files.
execution failed. Retries exceeded.: 0
Processing failed on last retry. Creating item but without proposals.
~~~

**Comment by eikek** [comment] 2020-10-01 14:13
Oh that seems to break at the db level. Which db are you using? Postgres, for example, states to support "any length" for the datatype text. But mariadb may not….

It's also interesting that it was somehow blocking. If it finally fails (after last retry), you should be able to at least see it and add metadata manually. Since the failure happened when storing metadata, there are no suggestions or anything. I need to reproduce it to see what's going on.

**Comment by Lucki** [comment] 2020-10-01 14:20
> Which db are you using?

I'm using mariadb which is Arch Linux's default implementation of MySQL.

> Since the failure happened when storing metadata, there are no suggestions or anything.

I guess text search is also unavailable?

> If it finally fails (after last retry), you should be able to at least see it and add metadata manually.

I could see this behavior on my second try.

**Comment by eikek** [comment] 2020-10-01 16:26
Lucki <notifications@github.com> writes:

>> Which db are you using?
>
> I'm using mariadb which is Arch Linux's default implementation of MySQL.

Ok, I just saw that in mariadb the `text` type is limited to 16kb… I'll
fix it to be a `longtext` for the next release. I need to double check
the syntax and then I can give you a sql snippet that you could execute
against your mariadb that transforms the data-type (as a workaround
until it is fixed in the next release).

>> Since the failure happened when storing metadata, there are no suggestions or anything.
>
> I guess text search is also unavailable?

Yes, that's true. However, once the column type is fixed, you can
trigger a re-processing.

>> If it finally fails (after last retry), you should be able to at least see it and add metadata manually.
>
> I could see this behavior on my second try.

Ok, at least something that "worked" :) I'll try reproduce it with large
pdf the next days.

**Comment by eikek** [comment] 2020-10-01 18:35
Here is a quick workaround: To fix the data model, run this against your database (this is safe to not loose data, but no guarantees here ;)):
``` sql
ALTER TABLE `attachmentmeta`
MODIFY COLUMN `content` longtext;

ALTER TABLE `attachmentmeta`
MODIFY COLUMN `nerlabels` longtext;

ALTER TABLE `attachmentmeta`
MODIFY COLUMN `itemproposals` longtext;
```
Then you can start reprocessing the item with (using bash):

``` shell
USER=…
PASS=…
ITEMID="9sW3Qz…cQQi"

LOGIN_URL="http://localhost:7880/api/v1/open/auth/login"
REPROCESS_URL="http://localhost:7880/api/v1/sec/item/$ITEMID/reprocess"

auth_token=$(curl --fail -XPOST --silent --data-binary "{\"account\":\"$USER\", \"password\":\"$PASS\"}" "$LOGIN_URL" | jq -r .token)
curl --fail -XPOST -H "X-Docspell-Auth: $auth_token" \
    -H 'Content-Type: application/json' \
    -d '{"ids":[]}' "$REPROCESS_URL"
```
Where you need to specify account, password and the item id that contains the files to reprocess.

**Comment by Lucki** [comment] 2020-10-02 11:43
Longtext worked :)

I've did a simple reupload to scan again, but there's still the same document somewhere invisible blocking so I had to disable the duplicate check.

**Comment by eikek** [comment] 2020-10-02 11:55
Yes, this is another bug that is being fixed with this one …

The problem is that the failing item is not updated correctly and so the processing task thinks, it already exists. It is an item in state `premature` or `processing` and is so not visible in the gui. You could set all to `created` with an sql update statement (from off my head: `update item set state = 'created'`). This should make the item visible in the ui (if it is this problem :)).

**Comment by Lucki** [comment] 2020-10-02 12:15
Yes, now I was able to delete the failed one and the February one. Sadly now all documents are displayed as new…

Interestingly it also showed me a third document which I haven't seen before, also no labels are suggested so I guess it has also failed before.
A reupload shows me `execution failed. Retrying later.: Invalid date 'February 29' as '2005' is not a leap year`, so yes, it's like the other one.

**Comment by eikek** [comment] 2020-10-02 12:32
Oh no, I'm so sorry - this update statement makes all items new :-/ I wrote too quickly without thinking a lot…. You could make _all_ "confirmed" again by using the same update statement with state `'confirmed'`. The date bug is being fixed, too. I guess I'll make a bugfix release soon. Thank you so much for reporting all this!

**Comment by Lucki** [comment] 2020-10-02 12:42
Great, now all is fine again.

**Closed** 2020-10-02 17:38 UTC
Labels: bug
