### ISSUE TITLE
Unable to Upload Documents in new Installation

### ISSUE THREAD

**Issue by pschichtel** [eikek/docspell#1966] opened 2023-02-20 00:44 UTC
I've just deployed a fresh instance of Docspell 0.39.0 backed by Postgres and S3 (Minio). I deployed it into a a single-node k8s using a handwritten helm chart.

After login in with an initial account, I attempted to upload various different objects, but I get get is "There were errors uploading some files.", the `/api/v1/sec/upload/item` API returns "There were no files to submit.". I've increased the log level of restserver to Debug, but it still doesn't produce any interesting logs beyong the request logging. The browser console is also clear (except 3 404 responses due to missing addons).

**Comment by eikek** [comment] 2023-02-20 09:34
Hi @pschichtel , unfortunately I have not really knowledge of k8s, so can't comment on this setup. The error you described means that there were no files reaching the endpoint. The upload is a multipart request and docspell couldn't find any files in it. Did you try via the webui? Maybe you could try curl in verbose mode and hope for some clues. If there is a reverse proxy involved, maybe this component does something to the request?

**Comment by pschichtel** [comment] 2023-02-20 09:48
@eikek I did try via web ui. the reverse proxy in between is an nginx (ingress-nginx), it's configuration seems to be in line with what the docspell documentation expects and when running tcpdump in the restserver container it seemed to receive requests including multipart data.

> Maybe you could try curl in verbose mode and hope for some clues.

do you mean the `/api/v1/sec/upload/item` request?

**Comment by eikek** [comment] 2023-02-20 10:21
Yes this is the endpoint, there are some examples here: https://docspell.org/docs/api/upload/

Strange then 🤔 , docspell reads the request as a `multipart/form-data` and looks for a `meta` part and one or more `file` parts. The `meta` part must be named like this and can contain metadata as json. Other parts are interpreted as binary files. The error _"There were no files to upload"_ is triggered if there are no binary file parts in the request. 

From past experience, I would suspect the nginx as the culprit :) maybe it's possible to do some portforwarding and skip the proxy just to see if it works "bare bones".

**Comment by pschichtel** [comment] 2023-02-20 10:27
> The meta part must be named like this and can contain metadata as json.

I've definitely seen that in the tcpdump output

> From past experience, I would suspect the nginx as the culprit :)

I'm assuming the same.

> maybe it's possible to do some portforwarding and skip the proxy just to see if it works "bare bones".

docspell itself doesn't verify the hostname it is accessed with, right? then that would easy, yes.

I'll have another stab at this later today, I'll keep you posted.

**Comment by eikek** [comment] 2023-02-20 10:41
> docspell itself doesn't verify the hostname it is accessed with, right? then that would be easy, yes.

By default, it doesn't (for convenience reasons :))… but you can set `base-url` to the external url you want docspell to be accessed by. Then it will be used to generate cookies and links etc and access from another url won't work most of the time - otoh it is not validated explicietely either (maybe this should be added 🤔)).

**Comment by pschichtel** [comment] 2023-02-20 23:30
@eikek I configured the service to be on a dedicated API, so I can directly access it on port 7880 without nginx, but the behavior is the same.

request:

```bash
curl -v -X POST -F meta='{"multiple":true,"flattenArchives":false,"direction":"incoming","folder":null,"skipDuplicates":true,"tags":null,"fileFilter":null,"language":null,"attachmentsOnly":null}' -F file=test.txt -H "Cookie: $COOKIE" http://10.1.0.111:7880/api/v1/sec/upload/item
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 10.1.0.111:7880...
* Connected to 10.1.0.111 (10.1.0.111) port 7880 (#0)
> POST /api/v1/sec/upload/item HTTP/1.1
> Host: 10.1.0.111:7880
> User-Agent: curl/7.88.1-DEV
> Accept: */*
> Cookie: ...
> Content-Length: 409
> Content-Type: multipart/form-data; boundary=------------------------0c8465c9c25be377
> 
* We are completely uploaded and fine
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Mon, 20 Feb 2023 23:26:06 GMT
< Content-Length: 60
< 
* Connection #0 to host 10.1.0.111 left intact
{"success":false,"message":"There were no files to submit."}
```

restserver logs:

```
2023.02.20 23:26:06:0000 [io-comp...] [DEBUG] docspell.restserver.routes.UploadRoutes - Parsed upload meta data: (true,UploadMeta(Some(Incoming),webapp,None,List(),true,docspell.common.Glob$$anon$1@732f6366,List(),None,None,Some(false)))
2023.02.20 23:26:06:0000 [io-comp...] [DEBUG] com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection org.postgresql.jdbc.PgConnection@7114b1c7
2023.02.20 23:26:06:0001 [io-comp...] [INFO ] docspell.backend.ops.OUpload.saveFile:208 - Receiving file File(None,None,Stream(..))
2023.02.20 23:26:06:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 POST /api/v1/sec/upload/item
2023.02.20 23:26:06:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 200 OK
```

**Comment by pschichtel** [comment] 2023-02-20 23:50
apparently my s3 configuration didn't work and that results in the same error. I guess something is swallowing errors there. After switch to filesystem it worked immediately

**Comment by pschichtel** [comment] 2023-02-21 00:45
I accidentally used `http://` instead of `https://` for my minio endpoint, which caused this behavior.

**Comment by eikek** [comment] 2023-02-21 07:11
Thanks for the update and analysis! I looked again at the code and indeed - this error message occurs when no files could be saved. I was not looking close enough yesterday :/. Sorry for misguiding you here! If the file backend cannot save a file and thus no files could be saved, this error will be given. The same error occurs, if there are no files in the request in the first place.
 
But... there should be error messages in the logs of the respective file backend. That is not the case if I understood correctly? (I need to setup minio later this week and try reproduce it, so far I didn't have time)

**Comment by pschichtel** [comment] 2023-02-21 10:13
`podman run -p 9000:9000 -p 9001:9001 quay.io/minio/minio server /data --console-address ":9001"` (or docker)

default admin user is `minioadmin:minioadmin` from their docs.

**Comment by eikek** [comment] 2023-02-26 10:11
Closing this as the issue is solved. The bad error reporting is now tracked in #1976

**Closed by eikek** 2023-02-26 10:11 UTC
Labels: question
