### ISSUE TITLE
Consumer not consuming

### ISSUE THREAD

**Issue by stepanov1975** [eikek/docspell#1244] opened 2021-12-29 10:38 UTC
I am running dockspell in docker using docker-compose
Consumer configured as below
I have collective "home" (i am logging in as "home/alex")
If I put file in ./consume_docs (mapped to /opt/docs) directory the log says:
```
Got: /opt/docs/0000067.pdf
Cmd: Watch: Error finding collective: The collective could not be deduced for /opt/docs/0000067.pdf. Make sure there is a subdirectory with the name of the collective below /opt/docs
Watching directory (Recursive): /opt/docs
```

If I create a directory home inside ./consume_docs and put the file in this directory I am getting:

```
Got: /opt/docs/home
Cmd: Watch: Error finding collective: The collective could not be deduced for /opt/docs/home. Make sure there is a subdirectory with the name of the collective below /opt/docs
Watching directory (Recursive): /opt/docs
```

Configuration:
```
consumedir:
    image: docspell/dsc:latest
    container_name: docspell-consumedir
    command:
      - dsc
      - "-d"
      - "http://docspell-restserver:7880"
      - "watch"
      - "--delete"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:..."
      - "/opt/docs"
    restart: unless-stopped
    volumes:
      - ./consume_docs:/opt/docs
    depends_on:
      - restserver

```

**Comment by eikek** [comment] 2021-12-29 20:40
That looks like a bug, but it's working for me. Hm, it looks like it wants to upload a directory and not the file. Is the file not uploaded? Is there anything special with your setup, like using NFS or similar?

You could  try a different version of the docker image, i.e. `docspell/dsc:v0.5.0`. If that is working, you can stick to this version for a while. I did changes in this area in the latest version (as its only change, next to library updates).

**Comment by didn0t** [comment] 2022-01-14 09:48
I'm seeing a similar issue.  Tried the different docker image but same result.  Similar configuration:

```
│   Watching directory (Recursive): /opt/docs                                                                                                                                                         │
│   Press Ctrl-C to quit.                                                                                                                                                                             │
│   ------------------------------------------------------------------------------                                                                                                                    │
│   Got: /opt/docs/paul/2021_09_19_12_59_52.pdf                                                                                                                                                       │
│   Cmd: Watch: Uploading failed: An http error occurred: An error was received from http://docspell-restserver:7880/api/v1/open/integration/checkfile/paul/a66e68174d697b0b6fc3aa7c7a8c9b3691a5b6d   │
│   ce5e9db25cd3bf57576054590: HTTP status client error (404 Not Found) for url (http://docspell-restserver:7880/api/v1/open/integration/checkfile/paul/a66e68174d697b0b6fc3aa7c7a8c9b3691a5b6dce5e   │
│   9db25cd3bf57576054590) 
```

```
│   level=INFO  thread=blaze-selector-6 logger=o.h.b.c.n.NIO1SocketServerGroup message="Accepted connection from /172.18.0.35:54430"                                                                  │
│   level=INFO  thread=io-compute-4 logger=o.h.s.m.Logger message="HTTP/1.1 GET /api/v1/open/integration/checkfile/paul/a66e68174d697b0b6fc3aa7c7a8c9b3691a5b6dce5e9db25cd3bf57576054590"             │
│   level=INFO  thread=io-compute-4 logger=o.h.s.m.Logger message="HTTP/1.1 404 Not Found"                                                                                                            │
```

Integration endpoint is enabled.

**Comment by eikek** [comment] 2022-01-14 21:59
Did you upgrade recently? I'm not sure, but it may be that there was a bug which ignored the collective setting for the integration endpoint.

It's true there are two configs: one is in the config file, so an administrator can disable it globally. Then each account (collective) can decide whether it should be enabled or not.

**Comment by eikek** [comment] 2022-04-09 14:08
This was fixed in docspell/dsc#113

**Closed by eikek** 2022-04-09 14:08 UTC
Labels: question

**Comment by ozgurulukir** [comment] 2025-01-23 10:05
Hi, I have similar problem, consumer is not consuming, installation done via docker-compose with latest information on homepage,
Everthing is working, no error on logs.

**Comment by eikek** [comment] 2025-01-23 19:28
@ozgurulukir could the cause be as suggested in #2903 ? did you create a collective directory?

**Comment by ozgurulukir** [comment] 2025-01-23 22:08
I have created the matching collective folder, but the consumer isn't capturing files. However, the Windows DSC binary is working fine; the watcher is capturing and uploading files to Docspell without issue.
