### ISSUE TITLE
Error while starting (it worked once the first time) - Feature not supported: "autoServerMode && (readOnly...

### ISSUE THREAD

**Issue by knowncolor** [eikek/docspell#503] opened 2020-12-09 14:38 UTC
I installed via `.deb` packages, restserver and joex, both have the same error during startup.
It worked the first time I ran them, I was able to create an account etc.

Any help appreciated.

```
[ioapp-compute-0] INFO  d.s.m.FlywayMigrate - Running db migrations... 
[ioapp-compute-0] INFO  d.s.m.FlywayMigrate - Using migration locations: List(classpath:db/migration/h2) 
[ioapp-compute-0] INFO  o.f.c.i.l.VersionPrinter - Flyway Community Edition 7.3.0 by Redgate 
org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:h2:///tmp/docspell-demo.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE) for user 'sa': Feature not supported: "autoServerMode && (readOnly || fileLockMethod == NO || fileLockMethod == FS || inMemory)" [50100-200]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : HYC00
Error Code : 50100
Message    : Feature not supported: "autoServerMode && (readOnly || fileLockMethod == NO || fileLockMethod == FS || inMemory)" [50100-200]
```

**Comment by eikek** [comment] 2020-12-09 17:24
Hi, sorry for this. I'm not sure what happened. Do you maybe have some specific filesystem in `/tmp`, can the user write to the location (the files `/tmp/docspell-demo*`)? 

Did this happen after an version upgrade of docspell?

**Comment by knowncolor** [comment] 2020-12-09 17:34
Hey dude, thanks for the quick response, I'm looking forward to using this tool.

I'm running pretty standard Ubuntu 20.

No write access to /tmp it looks like - could this be it?

```
ls -l /tmp/
total 192
-rw------- 1 bon      bon          0 Dec  9 14:00 config-err-5wZmx7
drwxr-xr-x 3 docspell docspell  4096 Dec  9 14:29 docspell-analysis
-rw-r--r-- 1 docspell docspell   139 Dec  9 14:29 docspell-demo.db.lock.db
-rw-r--r-- 1 docspell docspell 81920 Dec  9 17:29 docspell-demo.db.mv.db
-rw-r--r-- 1 docspell docspell  4366 Dec  9 13:59 docspell-demo.db.trace.db

```

**Comment by eikek** [comment] 2020-12-09 18:34
It looks good, actually. The user that runs the process(es) should be `docspell` and there is a `rw`. Hm. Can you find a `/tmp/.lock.db` file (when starting up)? Did you change anything in the config regarding this URL (`jdbc:h2:…`)? Can you think of anything that changed between the time it worked and now?

You could try to play with the url, try adding a `FILE_LOCK=SOCKET` option, like for example: `jdbc:h2:///tmp/docspell-demo.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE;FILE_LOCK=SOCKET`. I found posts about this where users reported that adding a `USER=sa` option helped – but I doubt it actually… still worth a try. Or maybe try (re)moving all these files in `/tmp` to see if starting with an empty db works.

Sorry, currently I don't really know what's going on. Just try guessing so more questions…

**Comment by knowncolor** [comment] 2020-12-12 14:36
Thanks for all your suggestions, `FILE_LOCK=SOCKET` made no difference. I removed all `/tmp/docspell*` files/dirs and it got further this time but another error...

```
[main] INFO  d.joex.Main - Using config file from system properties: /usr/share/docspell-joex/bin/../conf/docspell-joex.conf 
[main] INFO  d.joex.Main - 
***>  ______                          _ _
***>  |  _  \                        | | |
***>  | | | |___   ___ ___ _ __   ___| | |
***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
***>  |___/ \___/ \___|___/ .__/ \___|_|_|
***>                      | |
***>                      |_| v0.16.0 (#4682bf4a)
***>  << JOEX >>
***>  Id:       joex1
***>  Base-Url: http://localhost:7878
***>  Database: jdbc:h2:///tmp/docspell-demo.db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
***>  Fts:      -
***>  Config:   /usr/share/docspell-joex/bin/../conf/docspell-joex.conf
***>   
[ioapp-compute-0] INFO  d.s.m.FlywayMigrate - Running db migrations... 
[ioapp-compute-0] INFO  d.s.m.FlywayMigrate - Using migration locations: List(classpath:db/migration/h2) 
[ioapp-compute-0] INFO  o.f.c.i.l.VersionPrinter - Flyway Community Edition 7.3.0 by Redgate 
[ioapp-compute-0] INFO  o.f.c.i.d.b.DatabaseType - Database: jdbc:h2:///tmp/docspell-demo.db (H2 1.4) 
[ioapp-compute-0] INFO  o.f.c.i.s.JdbcTableSchemaHistory - Repair of failed migration in Schema History table "public"."flyway_schema_history" not necessary. No failed migration detected. 
[ioapp-compute-0] INFO  o.f.c.i.c.DbRepair - Successfully repaired schema history table "public"."flyway_schema_history" (execution time 00:00.087s). 
[ioapp-compute-0] INFO  o.f.c.i.l.VersionPrinter - Flyway Community Edition 7.3.0 by Redgate 
[ioapp-compute-0] INFO  o.f.c.i.c.DbValidate - Successfully validated 17 migrations (execution time 00:00.050s) 
[ioapp-compute-0] INFO  o.f.c.i.c.DbMigrate - Current version of schema "public": 1.13.0 
[ioapp-compute-0] INFO  o.f.c.i.c.DbMigrate - Schema "public" is up to date. No migration necessary. 
[docspell-joex-dbconnect-0] INFO  c.z.h.HikariDataSource - HikariPool-1 - Starting... 
[docspell-joex-dbconnect-0] INFO  c.z.h.HikariDataSource - HikariPool-1 - Start completed. 
[ioapp-compute-0] INFO  d.j.s.SchedulerImpl - Starting scheduler 
[ioapp-compute-1] INFO  d.j.s.PeriodicSchedulerImpl - Starting periodic scheduler 
[ioapp-compute-2] INFO  d.b.ops.ONode - Registering node joex1 
[ioapp-compute-1] DEBUG d.j.s.PeriodicSchedulerImpl - Going into main loop 
[ioapp-compute-1] DEBUG d.j.s.PeriodicSchedulerImpl - Looking for next periodic task 
[ioapp-compute-0] DEBUG d.j.s.SchedulerImpl - Try to acquire permit (2 free) 
[ioapp-compute-0] DEBUG d.j.s.SchedulerImpl - New permit acquired 
[ioapp-compute-1] DEBUG d.j.s.PeriodicSchedulerImpl - Found periodic task 'Docspell house-keeping/Sun *-*-* 00:00:00' 
[ioapp-compute-1] DEBUG d.j.s.PeriodicSchedulerImpl - Scheduling next notify for timer Sun *-*-* 00:00:00 -> Some(2020-12-13T00:00) 
[ioapp-compute-2] DEBUG d.j.s.SchedulerImpl - Next job found: Some(2fF88khCP.../docspell-system/all-previews/Low) 
[ioapp-compute-2] DEBUG d.j.s.SchedulerImpl - Creating context for job 2fF88khCP.../docspell-system/all-previews/Low to run JobTask(Ident(all-previews),docspell.joex.scheduler.Task$$anonfun$contramap$4@3e1b4f34,docspell.joex.scheduler.Task$$anonfun$contramap$4@3f5f0659) 
[ioapp-compute-1] DEBUG d.j.s.PeriodicSchedulerImpl - Waiting for notify 
[ioapp-compute-2] DEBUG d.j.s.SchedulerImpl - Forking job 2fF88khCP.../docspell-system/all-previews/Low 
[ioapp-compute-1] DEBUG d.j.s.SchedulerImpl - Starting task now 
[ioapp-compute-2] DEBUG d.j.s.SchedulerImpl - Try to acquire permit (1 free) 
[ioapp-compute-2] DEBUG d.j.s.SchedulerImpl - New permit acquired 
[ioapp-compute-0] INFO  d.j.s.LogSink - >>> 2020-12-12T14:31:10.468159Z Info 2fF88khCP.../docspell-system/all-previews/Low: Generating previews for attachments 
[ioapp-compute-3] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-0 
[ioapp-compute-3] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-1 
[ioapp-compute-3] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-2 
[ioapp-compute-3] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-3 
[ioapp-compute-3] INFO  o.h.b.c.n.SelectorLoop - Shutting down SelectorLoop blaze-selector-4 
[ioapp-compute-3] INFO  d.b.ops.ONode - Unregister app joex1 
[ioapp-compute-1] INFO  c.z.h.HikariDataSource - HikariPool-1 - Shutdown initiated... 
[ioapp-compute-3] DEBUG d.j.s.SchedulerImpl - Next job found: Some(FM9F7ueq2.../docspell-system/all-page-count/Low) 
[ioapp-compute-3] DEBUG d.j.s.SchedulerImpl - Creating context for job FM9F7ueq2.../docspell-system/all-page-count/Low to run JobTask(Ident(all-page-count),docspell.joex.scheduler.Task$$anonfun$contramap$4@b54660a,docspell.joex.scheduler.Task$$anonfun$contramap$4@7b2ebe67) 
[ioapp-compute-3] DEBUG d.j.s.SchedulerImpl - Forking job FM9F7ueq2.../docspell-system/all-page-count/Low 
[ioapp-compute-3] DEBUG d.j.s.SchedulerImpl - Try to acquire permit (0 free) 
[ioapp-compute-0] INFO  d.j.s.LogSink - >>> 2020-12-12T14:31:10.566057Z Info 2fF88khCP.../docspell-system/all-previews/Low: Submitted 0 jobs 
[ioapp-compute-1] INFO  c.z.h.HikariDataSource - HikariPool-1 - Shutdown completed. 
[ioapp-compute-1] INFO  o.h.c.PoolManager - Shutting down connection pool: curAllocated=0 idleQueues.size=0 waitQueue.size=0 maxWaitQueueLimit=256 closed=false 
java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.Net.bind(Net.java:447)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
	at java.base/java.nio.channels.ServerSocketChannel.bind(ServerSocketChannel.java:162)
	at org.http4s.blaze.channel.nio1.NIO1SocketServerGroup.$anonfun$bind$1(NIO1SocketServerGroup.scala:225)
	at map @ org.http4s.server.blaze.BlazeServerBuilder.mkServerChannel$1(BlazeServerBuilder.scala:345)
	at make @ docspell.common.ThreadFactories$.executorResource(ThreadFactories.scala:42)
	at make @ docspell.common.ThreadFactories$.executorResource(ThreadFactories.scala:42)
	at flatMap @ fs2.internal.CompileScope.acquireResource(CompileScope.scala:180)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$12(Algebra.scala:511)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
	at flatMap @ fs2.internal.CompileScope.$anonfun$acquireResource$4(CompileScope.scala:185)
	at flatten @ fs2.internal.ScopedResource$$anon$1.acquired(ScopedResource.scala:139)
	at flatMap @ fs2.internal.CompileScope.$anonfun$acquireResource$1(CompileScope.scala:183)
	at make @ docspell.common.ThreadFactories$.executorResource(ThreadFactories.scala:42)
	at make @ docspell.common.ThreadFactories$.executorResource(ThreadFactories.scala:42)
	at flatMap @ fs2.internal.CompileScope.acquireResource(CompileScope.scala:180)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$12(Algebra.scala:511)
	at flatMap @ fs2.internal.FreeC$.interruptGuard$1(Algebra.scala:436)
java.util.concurrent.RejectedExecutionException: Task cats.effect.internals.IOShift$Tick@7fc9f405 rejected from java.util.concurrent.ThreadPoolExecutor@7e7aef29[Shutting down, pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 24]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at cats.effect.internals.IOShift$$anon$1.apply(IOShift.scala:29)
	at cats.effect.internals.IOShift$$anon$1.apply(IOShift.scala:27)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:439)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:155)
	at cats.effect.internals.IORunLoop$.restart(IORunLoop.scala:40)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:48)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:34)
	at cats.effect.internals.IOAsync$.$anonfun$apply$1(IOAsync.scala:37)
	at cats.effect.internals.IOAsync$.$anonfun$apply$1$adapted(IOAsync.scala:37)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:439)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:155)
	at cats.effect.internals.IORunLoop$.restart(IORunLoop.scala:40)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:48)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:34)
	at cats.effect.internals.IOAsync$.$anonfun$apply$1(IOAsync.scala:37)
	at cats.effect.internals.IOAsync$.$anonfun$apply$1$adapted(IOAsync.scala:37)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:439)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:155)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:457)
	at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:466)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:474)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:414)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:122)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:455)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:476)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:414)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.util.concurrent.RejectedExecutionException: Task cats.effect.internals.IOShift$Tick@74f35cb4 rejected from java.util.concurrent.ThreadPoolExecutor@7e7aef29[Shutting down, pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 24]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at cats.effect.internals.IOShift$$anon$1.apply(IOShift.scala:29)
	at cats.effect.internals.IOShift$$anon$1.apply(IOShift.scala:27)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:439)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:155)
	at cats.effect.internals.IORunLoop$.restart(IORunLoop.scala:40)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:48)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:34)
	at cats.effect.internals.IOAsync$.$anonfun$apply$1(IOAsync.scala:37)
	at cats.effect.internals.IOAsync$.$anonfun$apply$1$adapted(IOAsync.scala:37)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:439)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:155)
	at cats.effect.internals.IORunLoop$.restart(IORunLoop.scala:40)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1(IOBracket.scala:48)
	at cats.effect.internals.IOBracket$.$anonfun$apply$1$adapted(IOBracket.scala:34)
	at cats.effect.internals.IOAsync$.$anonfun$apply$1(IOAsync.scala:37)
	at cats.effect.internals.IOAsync$.$anonfun$apply$1$adapted(IOAsync.scala:37)
	at cats.effect.internals.IORunLoop$RestartCallback.start(IORunLoop.scala:439)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:155)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:457)
	at cats.effect.internals.IORunLoop$RestartCallback.run(IORunLoop.scala:466)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:474)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:414)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:122)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:455)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:476)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:414)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by eikek** [comment] 2020-12-12 16:58
Hi, at least this error is a bit clearer now. The `Address already in use` indicates that some other process holds the port `7878` on your machine. Maybe there is another joex that has not been shutdown properly? Or some other application using this port?

**Comment by knowncolor** [comment] 2020-12-14 14:17
Such a silly error, docspell was already running on startup (it didn't start automatically when I first installed it, only after a reboot which confused me).

I tried uploading a document and it failed to process... looks like I need tesseract which I will install but didn't see this mentioned in the getting started instructions...

```
2020-12-14T13:54:47: Converting file Some(ebay-refund.png) (image/png) into a PDF
2020-12-14T13:54:47: Storing input to file /tmp/docspell-convert/docspell-tesseract4245872252464640815/infile for running tesseract
2020-12-14T13:54:47: Running external command: tesseract /tmp/docspell-convert/docspell-tesseract4245872252464640815/infile out -l deu pdf txt
2020-12-14T13:54:47: PDF conversion failed: Cannot run program "tesseract" (in directory "/tmp/docspell-convert/docspell-tesseract4245872252464640815"): error=2, No such file or directory. Go without PDF file
2020-12-14T13:54:47: Starting text extraction for 1 files
2020-12-14T13:54:47: Extracting text for attachment ebay-refund.png
2020-12-14T13:54:47: Running external command: tesseract stdin stdout -l deu
2020-12-14T13:54:47: Cannot extract text: Cannot run program "tesseract": error=2, No such file or directory. Try with converted file
2020-12-14T13:54:47: Cannot extract text
2020-12-14T13:54:47: Extracting text for attachment ebay-refund.png finished in 69 ms
```

**Comment by eikek** [comment] 2020-12-14 14:23
Yes, it needs tesseract and also some other tools (some of them can be disabled or are optional, if you don't need them). This should (hopefully) all be mentioned on the [prerequisite](https://docspell.org/docs/install/prereq/) page. The get-started section on the front-page only mentiones the "docker way", since this takes care of everything. When installing the zip or deb files, [this](https://docspell.org/docs/install/installing/#download-unpack-run) would be the page.  If you find anything missing there, let me know! :-) thanks!

The deb packages come with a systemd unit file, and they are started on boot.

**Comment by knowncolor** [comment] 2020-12-14 14:25
I missed that page - thank you!

**Comment by eikek** [comment] 2021-01-02 14:03
Hi @knowncolor, does dour problems remain or did you manage it somehow? Wondering if this issue can be closed or if I can be of further help?

**Comment by knowncolor** [comment] 2021-01-04 17:44
@eikek I decided that for personal use and running on my home machine the whole thing just felt too heavy. Setting up SOLR was the straw that broke the back in the end. I can't use docker as it does not play well with my VPN setup.

DocSpell looks like a great product and I wish you continued success, I would be back in a heartbeat if I needed this for a business setup.

**Comment by eikek** [comment] 2021-01-04 19:50
No worries, and thank you a lot for your feedback and interest! It is much appreciated. I'm curious now what the problem is with solr? I usually find it easy to install, is fast and it is quite light imho (runs for me with 50-400m ram, depending of course how much data and how many users etc, but for a 1-3 people/apps and "home data amount" it's ok). I think I miss something. Or what option would be a better fit in your case (I have other backends on the list, so I'm interested …).

But I know that the joex is currently very heavy, I'm going ot work on this. But things like ocr and the ai will continue to need memory; it will not go down that much (without sacrificing features).

**Comment by eikek** [comment] 2021-01-11 23:43
So I'm closing this. If you have any further questions/issues etc just get in touch :-)

**Closed by eikek** 2021-01-11 23:43 UTC
